export const mockups = {
  hero: "/placeholder/hero.png",
  problemStudent: "/placeholder/student-empty-cv.png",
  problemUMKM: "/placeholder/umkm-struggle.png",
  ecosystem: "/images/dashboardimage.png",
  howItWorks: {
    step1: "/images/langkah1.png",
    step2: "/images/langkah2.png",
    step3: "/images/langkah3.png",
    step4: "/images/langkah4.png",
    step5: "/images/langkah5.png",
    step6: "/images/langkah6.png",
    step7: "/images/langkah7.png",
    step8: "/images/langkah8.png",
  },
  marketplace: "/images/marketplace.png",
  escrow: "/images/langkah7.png",
  studentRank: "/placeholder/student-rank.png",
  portfolioBuilder: "/images/cv.png",
  taskHistory: "/images/chat.png",
  aiSop: "/placeholder/ai-sop-generator.png",
  aiQuality: "/placeholder/ai-quality-gate.png",
  matchmaking: "/placeholder/matchmaking.png",
  learningRecs: "/placeholder/learning-recommendation.png",
  timeline: "/placeholder/timeline.png",
  beforeProfile: "/placeholder/before-student-profile.png",
  afterProfile: "/placeholder/after-student-profile.png",
  recruiter: "/placeholder/recruiter.png",
  finalProduct: "/placeholder/final-product.png",
};
