export const mockups = {
  hero: "/placeholder/hero.png",
  problemStudent: "/placeholder/student-empty-cv.png",
  problemUMKM: "/placeholder/umkm-struggle.png",
  ecosystem: "/placeholder/bantu-ecosystem.png",
  howItWorks: {
    step1: "/placeholder/step1-post-task.png",
    step2: "/placeholder/step2-ai-sop.png",
    step3: "/placeholder/step3-accept-task.png",
    step4: "/placeholder/step4-upload-progress.png",
    step5: "/placeholder/step5-ai-quality.png",
    step6: "/placeholder/step6-approve-work.png",
    step7: "/placeholder/step7-payment.png",
    step8: "/placeholder/step8-portfolio.png",
  },
  marketplace: "/placeholder/marketplace.png",
  escrow: "/placeholder/escrow.png",
  studentRank: "/placeholder/student-rank.png",
  portfolioBuilder: "/placeholder/portfolio-builder.png",
  taskHistory: "/placeholder/task-history.png",
  aiSop: "/placeholder/ai-sop-generator.png",
  aiQuality: "/placeholder/ai-quality-gate.png",
  matchmaking: "/placeholder/matchmaking.png",
  learningRecs: "/placeholder/learning-recommendation.png",
  timeline: "/placeholder/timeline.png",
  beforeProfile: "/placeholder/before-student-profile.png",
  afterProfile: "/placeholder/after-student-profile.png",
  recruiter: "/placeholder/recruiter.png",
  finalProduct: "/placeholder/final-product.png",
};
